// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4kh11KHcBJje8KwEdLebndB3yeW3iiCA',
    appId: '1:241406769175:web:89d12104f2e6d0db4a8452',
    messagingSenderId: '241406769175',
    projectId: 'dashdine-f1f7c',
    authDomain: 'dashdine-f1f7c.firebaseapp.com',
    storageBucket: 'dashdine-f1f7c.appspot.com',
    measurementId: 'G-PK8C94G7NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhHgBSrpW1rZE_iPhkOD96m6hqxC0px_U',
    appId: '1:241406769175:android:af2b40ba1cf9c9d64a8452',
    messagingSenderId: '241406769175',
    projectId: 'dashdine-f1f7c',
    storageBucket: 'dashdine-f1f7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfMpXTxL-rfhYV5jSE2mcMUekmPSDdid8',
    appId: '1:241406769175:ios:6172603130e885974a8452',
    messagingSenderId: '241406769175',
    projectId: 'dashdine-f1f7c',
    storageBucket: 'dashdine-f1f7c.appspot.com',
    iosBundleId: 'com.example.dashDine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfMpXTxL-rfhYV5jSE2mcMUekmPSDdid8',
    appId: '1:241406769175:ios:5689901e3baf9c334a8452',
    messagingSenderId: '241406769175',
    projectId: 'dashdine-f1f7c',
    storageBucket: 'dashdine-f1f7c.appspot.com',
    iosBundleId: 'com.example.dashDine.RunnerTests',
  );
}
